### ISSUE TITLE
2.5	About You - Label Postcode as Eircode (Optional)

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#13]
Label Postcode as Eircode (Optional), Make it optional, Link to Find Eircode (Optional)  (https://finder.eircode.ie/#/)

**Comment by dessiekeegan** [comment]
Done

**Comment by paddykool** [comment]
Eircode is optional. Can create a profile without it.

**Comment by paddykool** [comment]
Eircode is not validated. I think its 7 characters/digits ?and can have a space (after the third)
@niamhmphelan - should the eircode text input have validation?

**Comment by paddykool** [comment]
oh - also, there's no link to Eircode ?

**Comment by dessiekeegan** [comment]
I Havent done the link..We can live without that IMO. The EIrcode should be optional. And it is. I added Eircode validation rule based off this document. Page 11.
[(https://www.eircode.ie/docs/default-source/Common/prepareyourbusinessforeircode-edition3published.pdf?sfvrsn=2)]

**Comment by niamhmphelan** [comment]
Eircode look up link is:
https://finder.eircode.ie/
See the current system redcross.ie/registerofpledges ,they have implemented it nicely there!

**Comment by dessiekeegan** [comment]
this is done now
