### ISSUE TITLE
3.3	Dashboard - The Are you an Organisation field value is not being displayed correctly in the dashboard.

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#20]
The Are you an Organisation field value is not being displayed correctly in the dashboard.

**Comment by dessiekeegan** [comment]
HI Paddy, if you read this. 
This is now resolved. I can close it or leave open for you to test before closing? What is your preference?

**Comment by paddykool** [comment]
Hi Dessie.
Eh - Up to yourself. If it's fairly obvious that it is resolved then close it nps.
Less work for me!
Going forward - close if obvious its fixed. Assign to me if there may be some work in testing it or was a 'finky' issue (or 'shitty' issue - cant think of a good word)
That sound cool? Make sense ?

**Comment by paddykool** [comment]
Actually - This needs more thought. I need to pull down the code before testing fixes.
I'll send a mail to all. Possibly add the issue number to  the commit and I'll see it in the history.
Probably best to assign all to me. Might be easier

**Comment by paddykool** [comment]
issue resolved
