### ISSUE TITLE
4a.4 Add a Time and Service Pledge - Are you in a position to travel to provide the service?

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#29]
4a.4 Are you in a position to travel to provide the service?

This is a new field (DB Change)
Please allow multi select with the following values: Limited Travel Options (Locally), Travel up to 10 miles, Travel Nationally, Travel Internationally.

**Comment by dessiekeegan** [comment]
Ive started on this one will finish

**Comment by dessiekeegan** [comment]
This is done. Needs a test tho it was complicated.

**Comment by paddykool** [comment]
![image](https://cloud.githubusercontent.com/assets/8235809/18028013/efe78020-6c6a-11e6-83c7-d842e2c42623.png)

'Are you in a position to travel' field pre-populated with code. See attached.

Free text field - should be drop down ?
When typing it tries to pre-populate 
@niamhmphelan - I take it this should be a drop down that can have multi selects yah ?

**Comment by paddykool** [comment]
Ok - got the multi select thing - I take it its the same input type as 'Nearby Facilities'.
Anywho - options are shown here (Didn't think they were the first time but will keep an eye)
Filed still get pre-populated with code though.

**Comment by dessiekeegan** [comment]
The Code is now replaced with "Please select"
