### ISSUE TITLE
4b.3 Add a Goods and Gifts Pledge - What condition are the items in? (DB Change Usable, Needs minor repairs, Needs major repairs) 

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#35]
4a.3 What condition are the items in? (DB Change Usable, Needs minor repairs, Needs major repairs)

**Comment by dessiekeegan** [comment]
Goods condition now shows the three options as above

**Comment by dessiekeegan** [comment]
This was done last week. 
Did you check it??
Note The label just reads "Goods Condition".

**Comment by paddykool** [comment]
This label is not available if furniture is selected. It is available if Technology is selected.

@niamhmphelan @dessiekeegan should it be available for all categories ???
