### ISSUE TITLE
4c.1 Add Accommodation Pledge - Change labels on address fields to match those on About You.

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#37]
Change labels on address fields to match those on About You.

**Comment by niamhmphelan** [comment]
2.2	Address Line 2 should be optional

2.3	Label Townland/Town/City as City/Town/Village

2.4	Label State/Province/Region as County

2.5	Label Postcode as Eircode (Optional), Make it optional, Link to Find Eircode (Optional)  (https://finder.eircode.ie/#/)

**Comment by dessiekeegan** [comment]
I had started this and finished most of it.. assigning myself.

**Comment by dessiekeegan** [comment]
Done> ready for tesht.

**Comment by paddykool** [comment]
All looks good
