### ISSUE TITLE
Offer Goods/Items/Medicine - new/used drop down incorrect

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#53]
Drop for new or used has incorrect selections:

![image](https://cloud.githubusercontent.com/assets/8235809/18649207/25e12de0-7eb6-11e6-9782-4e030ea2c81a.png)

Should be just
- New
- Used

Niamho - do you concur  ?

**Comment by dessiekeegan** [comment]
just fixed this i did
