### ISSUE TITLE
Offer Accommodation - Defaults to 'Select Country' and errors

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#54]
Add accommodation: Country defaults to select country, Then errors so cannot save pledge

![image](https://cloud.githubusercontent.com/assets/8235809/18768289/1f65fba4-811c-11e6-81bc-fabe9bbc770c.png)

**Comment by dessiekeegan** [comment]
I can't reproduce this one.. For me it defaults to Ireland every time... Can you give me the steps you did to reproduce? IS it on the admin side or the public facing side?

**Comment by dessiekeegan** [comment]
this stuff has been updated so is probably not an issue anyway.(thats not to say theres no other new issues:)

**Comment by paddykool** [comment]
Hi @dessiekeegan 
Sorry man - I haven't got round to replying to your comments. Will make time tonight.
Anywho - yah, I think the server had stopped on my machine or something.
Not sure but will comment correctly tonight
