### ISSUE TITLE
Offer accommodation -'Same as profile address' does not work

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#55]
Offer accommodation -'Same as profile address' does not work

![image](https://cloud.githubusercontent.com/assets/8235809/18768445/12ffb73c-811d-11e6-9904-36bb3a0fbac1.png)

**Comment by dessiekeegan** [comment]
This also works for me.

**Comment by dessiekeegan** [comment]
This has been updated now..Tested it and it seems fine. I've added the goods and the service ones also. And put them at the bottom of the pledge.
