### ISSUE TITLE
Time and Skills - Are you in a position to travel to provide the service - no options

### ISSUE THREAD

**Issue by paddykool** [niamhmphelan/pledge#56]
Typing yes/No does not bring up any options.
This fields should perhaps be a dropdown ??

![image](https://cloud.githubusercontent.com/assets/8235809/18768746/4ac322ec-811f-11e6-8235-6897c6f14b1b.png)

**Comment by dessiekeegan** [comment]
This is a multi select with four options. And it works for me.. On both Firefox and Chrome. I'd expect this if you killed the server.. Its populated at modal load.
